apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-scheduler
  template:
    metadata:
      labels:
        app: drift-scheduler
    spec:
      securityContext:
        runAsUser: 0       
        runAsGroup: 0       
        fsGroup: 0
      serviceAccountName: drift-scheduler
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: drift-scheduler
        image: crater-harbor.act.buaa.edu.cn/user-zhangry/drift-k8s-scheduler:v5
        imagePullPolicy: IfNotPresent
        command: ["/drift-scheduler"]
        args:
        - --config=/etc/kubernetes/scheduler-config.yaml
        - --v=4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        volumeMounts:
        - name: config
          mountPath: /etc/kubernetes/scheduler-config.yaml
          subPath: scheduler-config.yaml
          readOnly: true
        - name: kubeconfig
          mountPath: /etc/kubernetes/scheduler.conf
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: drift-scheduler-config
      - name: kubeconfig
        hostPath:
          path: /etc/kubernetes/scheduler.conf
          type: File
