apiVersion: v1
kind: ConfigMap
metadata:
  name: drift-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |-
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    clientConnection:
      kubeconfig: /etc/kubernetes/scheduler.conf
    profiles:
    - schedulerName: drift-scheduler
      plugins:
        filter:
          disabled:
          - name: NodeResourcesFit
          enabled:
          - name: DriftPlugin
        score:
          disabled:
          - name: "*"
          enabled:
          - name: DriftPlugin
            weight: 1
